export const ENHANCE_ROWS = [
  {
    id: 1,
    level: "1강",
    lowStone: 1,
    midStone: 0,
    highStone: 0,
    gold: 5000,
    ruby: 0,
    rate: "100%",
  },
  {
    id: 2,
    level: "2강",
    lowStone: 2,
    midStone: 0,
    highStone: 0,
    gold: 25000,
    ruby: 0,
    rate: "100%",
  },
  {
    id: 3,
    level: "3강",
    lowStone: 2,
    midStone: 0,
    highStone: 0,
    gold: 50000,
    ruby: 0,
    rate: "80%",
  },
  {
    id: 4,
    level: "4강",
    lowStone: 3,
    midStone: 1,
    highStone: 0,
    gold: 100000,
    ruby: 0,
    rate: "80%",
  },
  {
    id: 5,
    level: "5강",
    lowStone: 3,
    midStone: 1,
    highStone: 0,
    gold: 130000,
    ruby: 0,
    rate: "70%",
  },
  {
    id: 6,
    level: "6강",
    lowStone: 4,
    midStone: 2,
    highStone: 1,
    gold: 150000,
    ruby: 0,
    rate: "50%",
  },
  {
    id: 7,
    level: "7강",
    lowStone: 4,
    midStone: 2,
    highStone: 1,
    gold: 170000,
    ruby: 5,
    rate: "40%",
  },
  {
    id: 8,
    level: "8강",
    lowStone: 6,
    midStone: 3,
    highStone: 2,
    gold: 300000,
    ruby: 5,
    rate: "30%",
  },
  {
    id: 9,
    level: "9강",
    lowStone: 6,
    midStone: 3,
    highStone: 2,
    gold: 350000,
    ruby: 5,
    rate: "20%",
  },
  {
    id: 10,
    level: "10강",
    lowStone: 8,
    midStone: 4,
    highStone: 3,
    gold: 500000,
    ruby: 10,
    rate: "10%",
  },
  {
    id: 11,
    level: "11강",
    lowStone: 8,
    midStone: 4,
    highStone: 3,
    gold: 700000,
    ruby: 10,
    rate: "5%",
  },
  {
    id: 12,
    level: "12강",
    lowStone: 8,
    midStone: 4,
    highStone: 3,
    gold: 1000000,
    ruby: 10,
    rate: "3%",
  },
  {
    id: 13,
    level: "13강",
    lowStone: 10,
    midStone: 6,
    highStone: 4,
    gold: 1300000,
    ruby: 30,
    rate: "2%",
  },
  {
    id: 14,
    level: "14강",
    lowStone: 10,
    midStone: 6,
    highStone: 4,
    gold: 1500000,
    ruby: 30,
    rate: "1%",
  },
  {
    id: 15,
    level: "15강",
    lowStone: 10,
    midStone: 6,
    highStone: 5,
    gold: 2000000,
    ruby: 30,
    rate: "1%",
  },
];

export const PICKAXE_DATA = [
  { stage: "1강", power: 20, speed: 1.5, drops: 2, rare: "0%", exp: 3 },
  { stage: "2강", power: 25, speed: 1.5, drops: 3, rare: "1%", exp: 3 },
  { stage: "3강", power: 30, speed: 1.5, drops: 3, rare: "1%", exp: 10 },
  { stage: "4강", power: 40, speed: 1.5, drops: 3, rare: "2%", exp: 16 },
  { stage: "5강", power: 50, speed: 1.5, drops: 4, rare: "2%", exp: 33 },
  { stage: "6강", power: 60, speed: 1.5, drops: 4, rare: "3%", exp: 34 },
  { stage: "7강", power: 100, speed: 1.5, drops: 4, rare: "3%", exp: 36 },
  { stage: "8강", power: 110, speed: 1.5, drops: 5, rare: "4%", exp: 50 },
  { stage: "9강", power: 120, speed: 1.5, drops: 5, rare: "5%", exp: 50 },
  { stage: "10강", power: 130, speed: 1.0, drops: 5, rare: "6%", exp: 51 },
  { stage: "11강", power: 140, speed: 1.0, drops: 6, rare: "7%", exp: 51 },
  { stage: "12강", power: 150, speed: 1.0, drops: 6, rare: "8%", exp: 51 },
  { stage: "13강", power: 160, speed: 1.0, drops: 7, rare: "10%", exp: 68 },
  { stage: "14강", power: 170, speed: 1.0, drops: 7, rare: "13%", exp: 81 },
  { stage: "15강", power: 180, speed: 0.5, drops: 12, rare: "15%", exp: 102 },
];

export const HOE_DATA = [
  { stage: "1강", power: 22, speed: 0.7, drops: 2, exp: 1 },
  { stage: "2강", power: 24, speed: 0.7, drops: 3, exp: 1 },
  { stage: "3강", power: 30, speed: 0.7, drops: 3, exp: 2 },
  { stage: "4강", power: 33, speed: 0.7, drops: 3, exp: 4 },
  { stage: "5강", power: 35, speed: 0.7, drops: 4, exp: 8 },
  { stage: "6강", power: 50, speed: 0.7, drops: 4, exp: 9 },
  { stage: "7강", power: 53, speed: 0.7, drops: 4, exp: 9 },
  { stage: "8강", power: 57, speed: 0.7, drops: 5, exp: 13 },
  { stage: "9강", power: 60, speed: 0.7, drops: 5, exp: 13 },
  { stage: "10강", power: 70, speed: 0.5, drops: 5, exp: 13 },
  { stage: "11강", power: 73, speed: 0.5, drops: 6, exp: 13 },
  { stage: "12강", power: 77, speed: 0.5, drops: 6, exp: 13 },
  { stage: "13강", power: 80, speed: 0.5, drops: 7, exp: 17 },
  { stage: "14강", power: 85, speed: 0.5, drops: 7, exp: 20 },
  { stage: "15강", power: 100, speed: 0.3, drops: 12, exp: 34 },
];

export const FISHINGROD_DATA = [
  {
    stage: "1강",
    timeReduce: "6%",
    waterDrops: 1,
    fishPower: 17,
    fishSpeed: 1,
    treasureRate: "0%",
    minigameSkill: "10%",
    baitDrops: 1,
    nutExp: 5,
    fishExp: 2,
  },
  {
    stage: "2강",
    timeReduce: "10%",
    waterDrops: 1,
    fishPower: 20,
    fishSpeed: 1,
    treasureRate: "1%",
    minigameSkill: "20%",
    baitDrops: 1,
    nutExp: 5,
    fishExp: 2,
  },
  {
    stage: "3강",
    timeReduce: "14%",
    waterDrops: 1,
    fishPower: 22,
    fishSpeed: 1,
    treasureRate: "1%",
    minigameSkill: "20%",
    baitDrops: 2,
    nutExp: 5,
    fishExp: 6,
  },
  {
    stage: "4강",
    timeReduce: "18%",
    waterDrops: 1,
    fishPower: 25,
    fishSpeed: 1,
    treasureRate: "1%",
    minigameSkill: "30%",
    baitDrops: 2,
    nutExp: 5,
    fishExp: 10,
  },
  {
    stage: "5강",
    timeReduce: "23%",
    waterDrops: 1,
    fishPower: 30,
    fishSpeed: 1,
    treasureRate: "2%",
    minigameSkill: "30%",
    baitDrops: 2,
    nutExp: 5,
    fishExp: 21,
  },
  {
    stage: "6강",
    timeReduce: "27%",
    waterDrops: 1,
    fishPower: 35,
    fishSpeed: 1,
    treasureRate: "2%",
    minigameSkill: "40%",
    baitDrops: 3,
    nutExp: 5,
    fishExp: 22,
  },
  {
    stage: "7강",
    timeReduce: "31%",
    waterDrops: 1,
    fishPower: 45,
    fishSpeed: 1,
    treasureRate: "2%",
    minigameSkill: "40%",
    baitDrops: 3,
    nutExp: 5,
    fishExp: 22,
  },
  {
    stage: "8강",
    timeReduce: "35%",
    waterDrops: 1,
    fishPower: 50,
    fishSpeed: 1,
    treasureRate: "3%",
    minigameSkill: "50%",
    baitDrops: 3,
    nutExp: 5,
    fishExp: 32,
  },
  {
    stage: "9강",
    timeReduce: "39%",
    waterDrops: 1,
    fishPower: 57,
    fishSpeed: 1,
    treasureRate: "3%",
    minigameSkill: "50%",
    baitDrops: 4,
    nutExp: 5,
    fishExp: 32,
  },
  {
    stage: "10강",
    timeReduce: "44%",
    waterDrops: 1,
    fishPower: 65,
    fishSpeed: 0.7,
    treasureRate: "3%",
    minigameSkill: "60%",
    baitDrops: 4,
    nutExp: 5,
    fishExp: 32,
  },
  {
    stage: "11강",
    timeReduce: "49%",
    waterDrops: 1,
    fishPower: 78,
    fishSpeed: 0.7,
    treasureRate: "5%",
    minigameSkill: "60%",
    baitDrops: 4,
    nutExp: 5,
    fishExp: 32,
  },
  {
    stage: "12강",
    timeReduce: "53%",
    waterDrops: 1,
    fishPower: 90,
    fishSpeed: 0.7,
    treasureRate: "5%",
    minigameSkill: "70%",
    baitDrops: 5,
    nutExp: 5,
    fishExp: 32,
  },
  {
    stage: "13강",
    timeReduce: "56%",
    waterDrops: 1,
    fishPower: 100,
    fishSpeed: 0.7,
    treasureRate: "5%",
    minigameSkill: "70%",
    baitDrops: 5,
    nutExp: 5,
    fishExp: 43,
  },
  {
    stage: "14강",
    timeReduce: "58%",
    waterDrops: 1,
    fishPower: 110,
    fishSpeed: 0.7,
    treasureRate: "5%",
    minigameSkill: "80%",
    baitDrops: 5,
    nutExp: 5,
    fishExp: 51,
  },
  {
    stage: "15강",
    timeReduce: "60%",
    waterDrops: 1,
    fishPower: 150,
    fishSpeed: 0.5,
    treasureRate: "10%",
    minigameSkill: "100%",
    baitDrops: 6,
    nutExp: 5,
    fishExp: 68,
  },
];
